### ISSUE TITLE
tree-union definition

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#6]
the definition has four clauses.
why not use just the first and last?
the two asymetrical cases should return the same result as the last clause.

**Comment by greenTara** [comment]
Do you mean the final definition for a single argument that is a set?

If so,
I agree that the second clause includes the first.
Otherwise, these definitions are recursive and the three clauses are needed so that the recursion terminates. In particular,
The second clause is needed as a base case for the third clause, in order to provide a value for
result-default = Tree-UNION({defaultPart(s)|s in S})

The third clause is needed for the fourth clause to provide a value for Tree-UNION(S<sub>k</sub>) 
Also the second clause is needed in the case that S-S<sub>k</sub> is a set of order 0 graphs.
